package unionFind.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import java.util.HashSet;
import java.util.Scanner;
import java.util.List;
import unionFind.operations;
import static org.junit.Assert.*;
import org.junit.*;
import static unionFind.operations.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.28 01:25:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class operationsTest {



  // Generated by ComTest BEGIN
  /** testMain107 */
  @Test
  public void testMain107() {    // operations: 107
    Object[] oneTwo = { "kiuru", "lokki", "rastas", "sorsa", "varis"} ; 
    Object[] math = { "hash", "number", "12", "divide", "subtract"} ; 
    Object[] abc = { "kalle", "1", "rastas", "12", "on"} ; 
    assertEquals("From: operations line: 122", "[kalle, 1, rastas, 12, on, kiuru, lokki, rastas, sorsa, varis]", Arrays.toString(operations.union(abc,oneTwo))); 
    assertEquals("From: operations line: 123", "[hash, number, 12, divide, subtract, kalle, 1, rastas, 12, on]", Arrays.toString(operations.union(math,abc))); 
    assertEquals("From: operations line: 128", "[kalle, 1, rastas, 12, on]", Arrays.toString(operations.find(abc, "rastas"))); 
    assertEquals("From: operations line: 129", "[kiuru, lokki, rastas, sorsa, varis]", Arrays.toString(operations.find(oneTwo, "lokki"))); 
  } // Generated by ComTest END
}